### ISSUE TITLE
design contribution

### ISSUE THREAD

**Issue by masudr4n4** [mvccore/mvccore#1]
Hallo @tomFlidr 
just got your projects and want to make a logo for this projects if you have any requirements then let me know and please tell more details about what is purpose of this projects.
I am open source project contributor and its totally free for open source projects
Thank you

**Comment by tomFlidr** [comment]
Hallo,
it's nice:-) The purpose of this project is to write the best MVC architecture for large, complex, multilanguage PHP applications. Only the necessary core for MVC applications. But still with the core to be able use any other PHP library or utility from Zend, Symphony or other. Then the purpose of this project is to rewrite everything after releasing version 5.0.0 into C# for .NET and Mono and into Node.JS with async support. It's complicated, but any better logotype is welcome:-)
